In [81]:
# load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [82]:
# load the excel sheet into a Dataframe
xls = pd.ExcelFile("UW_Churn_Pred_Data.xls")
# Load the Data Before Feb 13 sheet
data = pd.read_excel(xls, sheet_name="Legend")
data

,Sale Channel,Channels the device sold
0,Model,Device model
1,Warranty,If the customer purchased warranty for the device
2,Feedback,Customer feedback
3,Verification,Verified issues from our testing team
4,Defect / Damage type,Damage type
5,Responsible Party,The reason why the device is returned
6,Type,Return or Repair the device
7,Spare Parts Used if returned,If there any used parts from the box
8,Final Status,The device may be refurbed or sent back (Retur...
9,Customer Service Requested,How many times the CS been reached
10,Number of Sim,Number of SIM card detected in the device
11,Sim Country,Carrier origin of the firt slot sim card
12,Slot 1,First carrier
13,Slot 2,Second carrier
14,Sim Card,Sim card info
15,Screen Usage (s),Screen time used
16,App Uage (s),Favorite Apps
17,Bluetooth (# of pairs),How many Bluetooth pairs
18,Wifi/Internet Connection,If the device is connected to the internet
19,Wallpaper,How many times the wallpaper has been changed
20,Registered Email,If the customer registered email with us
21,last boot - activate,last boot date minus the activation date
22,last boot - interval,last boot date minus the alive detected date
23,interval date,the last date the device been detected ON
24,last boot date,The date when last reboot happened
25,activate date,The date when the device been activated
26,Age Range,Approximated customer age range

In [83]:
# load the excel sheet into a Dataframe
xls = pd.ExcelFile("UW_Churn_Pred_Data.xls")
# Load the Data Before Feb 13 sheet
data = pd.read_excel(xls, sheet_name="Data Before Feb 13")

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Device number         4995 non-null   int64
 1   Product/Model #       4995 non-null   object
 2   Month                 275 non-null    object
 3   Office Date           275 non-null    datetime64[ns]
 4   Office Time In        275 non-null    object
 5   Source                275 non-null    object
 6   Type                  269 non-null    object
 7   Warranty              264 non-null    object
 8   Defect / Damage type  264 non-null    object
 9   Responsible Party     264 non-null    object
 10  Final Status          263 non-null    object
 11  Churn                 274 non-null    float64
 12  sim_info              4884 non-null   object
 13  promotion_email       3175 non-null   float64
 14  register_email        4884 non-null   float64
 15  interval_date         4884 non-null   object
 16  last_boot_date        4884 non-null   object
 17  active_date           4884 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(13)
memory usage: 702.5+ KB

In [85]:
data.describe()

,Device number,Office Date,Churn,promotion_email,register_email
count,4.995000e+03,275,274.000000,3175.000000,4884.000000
mean,3.722009e+08,2024-10-19 04:48:00,0.908759,0.215748,0.608313
min,3.300054e+08,2024-04-03 00:00:00,0.000000,0.000000,0.000000
25%,3.300432e+08,2024-07-15 12:00:00,1.000000,0.000000,0.000000
50%,4.100101e+08,2024-12-09 00:00:00,1.000000,0.000000,1.000000
75%,4.100461e+08,2025-01-14 00:00:00,1.000000,0.000000,1.000000
max,4.100997e+08,2025-02-13 00:00:00,1.000000,1.000000,1.000000
std,3.994723e+07,NaN,0.288478,0.411405,0.488177

In [86]:
data.head()

,Device number,Product/Model #,Month,Office Date,Office Time In,Source,Type,Warranty,Defect / Damage type,Responsible Party,Final Status,Churn,sim_info,promotion_email,register_email,interval_date,last_boot_date,active_date
0,410006072,N10,December,2024-12-19,15:30:00,B2C Amazon,Return,Yes,No defect,Customer: Remorse,Refurb B,1.0,"[{""slot_index"":0,""carrier_name"":""Emergency cal...",1.0,1.0,2024-11-20 09:49:27,2024-11-07 00:00:45,2024-11-07 00:00:45
1,410006130,N10,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,uninserted,0.0,0.0,2025-02-13 08:25:03,2025-01-29 17:50:42,2024-11-16 18:09:08
2,410006155,N10,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""slot_index"":1,""carrier_name"":""T-Mobile"",""mc...",0.0,0.0,2025-02-13 05:10:44,2025-02-08 23:07:05,2024-10-29 23:53:38
3,410006171,N10,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""slot_index"":0,""carrier_name"":""T-Mobile"",""mc...",0.0,1.0,2025-02-13 15:47:10,2025-02-02 03:01:57,2024-11-30 01:33:57
4,410006213,N10,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{""slot_index"":0,""carrier_name"":""Emergency cal...",0.0,0.0,2025-02-13 22:35:48,2024-11-26 19:36:58,2024-11-26 19:36:58

In [87]:
# List of columns to drop
columns_to_drop = ['Device number', 'Product/Model #', 'Office Date', 'Office Time In', 'Final Status','Defect / Damage type']

# Drop the specified columns
data = data.drop(columns=columns_to_drop)

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              275 non-null    object
 1   Source             275 non-null    object
 2   Type               269 non-null    object
 3   Warranty           264 non-null    object
 4   Responsible Party  264 non-null    object
 5   Churn              274 non-null    float64
 6   sim_info           4884 non-null   object
 7   promotion_email    3175 non-null   float64
 8   register_email     4884 non-null   float64
 9   interval_date      4884 non-null   object
 10  last_boot_date     4884 non-null   object
 11  active_date        4884 non-null   object
dtypes: float64(3), object(9)
memory usage: 468.4+ KB

In [89]:
import json

# Function to classify sim_info into "inserted" or "uninserted"
def classify_sim_info(sim_info):
    # Check if sim_info is a JSON-like string
    if isinstance(sim_info, str) and sim_info != 'Unknown' and sim_info != '':
        try:
            # Try parsing the sim_info string as JSON
            parsed = json.loads(sim_info)
            
            # If it's a list and contains data, check for 'carrier_name'
            if isinstance(parsed, list) and parsed:
                carrier_name = parsed[0].get('carrier_name', None)
                if carrier_name and carrier_name != 'Unknown':
                    return 'inserted'
            return 'uninserted'
        except json.JSONDecodeError:
            # If it's not a valid JSON string, classify as uninserted
            return 'uninserted'
    else:
        return 'uninserted'  # Treat Unknown or empty as uninserted

# Apply the classification function to the 'sim_info' column
data['sim_info_status'] = data['sim_info'].apply(classify_sim_info)

# Display the updated DataFrame to verify the new 'sim_info_status' column
print(data[['sim_info', 'sim_info_status']].head())

                                            sim_info sim_info_status
0  [{"slot_index":0,"carrier_name":"Emergency cal...        inserted
1                                         uninserted      uninserted
2  [{"slot_index":1,"carrier_name":"T-Mobile","mc...        inserted
3  [{"slot_index":0,"carrier_name":"T-Mobile","mc...        inserted
4  [{"slot_index":0,"carrier_name":"Emergency cal...        inserted

In [90]:
data = data.drop(columns=['sim_info'])

In [ ]:
dates_feature = ['interval_date', 'last_boot_date', 'active_date']

# Function to convert Arabic numerals to Western numerals
def convert_arabic_numbers(text):
    arabic_digits = "٠١٢٣٤٥٦٧٨٩"
    western_digits = "0123456789"
    translation_table = str.maketrans(arabic_digits, western_digits)
    return text.translate(translation_table) if isinstance(text, str) else text

# Apply conversion before parsing datetime
for col in ['last_boot_date', 'interval_date', 'active_date']:
    data[col] = data[col].astype(str).apply(convert_arabic_numbers)  # Convert Arabic numerals
    data[col] = pd.to_datetime(data[col], errors='coerce')  # Convert to datetime, setting invalid values to NaT

# Calculate differences
data['last_boot - activate'] = (data['last_boot_date'] - data['active_date'])
data['interval - last_boot'] = (data['interval_date'] - data['last_boot_date'])
data['interval - activate'] = (data['interval_date'] - data['active_date'])

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [91]:
# Update Churn column based on interval - activate
data['Churn'] = (data['interval - activate'] > pd.Timedelta(days=30)).astype(int)

# Check the result
print(data[['last_boot - activate', 'interval - last_boot', 'interval - activate', 'Churn']].head(30))

KeyError: 'interval - activate'

In [ ]:
# # Apply the churn condition considering both `interval - activate` and `interval - last_boot`
# def classify_churn(row):
#     if row['interval - activate'] < pd.Timedelta(days=30):
#         # Check if the device is frequently rebooted
#         if row['interval - last_boot'] < pd.Timedelta(days=10) :
#             return 1  # Churned
#         else:
#             return 0  # Not churned
#     else:
#         return 1  # Churned

# # Apply the function to classify churn
# data['Churn'] = data.apply(classify_churn, axis=1)

# # Check the result
# print(data[['last_boot - activate', 'interval - last_boot', 'interval - activate', 'Churn']].head(30))

In [ ]:
# One-hot encoding for categorical features
data = pd.get_dummies(data, drop_first=True)
data

,Churn,promotion_email,register_email,interval_date,last_boot_date,active_date,last_boot - activate,interval - last_boot,interval - activate,Month_August,...,"sim_info_[{""slot_index"":1,""carrier_name"":""Verizon"",""mcc"":""311"",""mnc"":""480"",""gid"":""BA01660000000000""}]","sim_info_[{""slot_index"":1,""carrier_name"":""Verizon"",""mcc"":""311"",""mnc"":""480"",""gid"":""BAE0000000000000""}]","sim_info_[{""slot_index"":1,""carrier_name"":""Visible "",""mcc"":""311"",""mnc"":""480"",""gid"":""BAE2000000000000""}]","sim_info_[{""slot_index"":1,""carrier_name"":""Yas Togo"",""mcc"":""615"",""mnc"":""01"",""gid"":""00000000""}]","sim_info_[{""slot_index"":1,""carrier_name"":""Yas"",""mcc"":""608"",""mnc"":""02"",""gid"":""00000000""}]","sim_info_[{""slot_index"":1,""carrier_name"":""africell"",""mcc"":""619"",""mnc"":""05"",""gid"":""FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF""}]","sim_info_[{""slot_index"":1,""carrier_name"":""airtel"",""mcc"":""404"",""mnc"":""94"",""gid"":""FFFFFFFFFFFFFFFFFFFF""}]","sim_info_[{""slot_index"":1,""carrier_name"":""ethio tel"",""mcc"":""636"",""mnc"":""01"",""gid"":""FFFFFF""}]",sim_info_uninserted,sim_info_status_uninserted
0,0,1.0,1.0,2024-11-20 09:49:27,2024-11-07 00:00:45,2024-11-07 00:00:45,0 days 00:00:00,13 days 09:48:42,13 days 09:48:42,False,...,False,False,False,False,False,False,False,False,False,False
1,1,0.0,0.0,2025-02-13 08:25:03,2025-01-29 17:50:42,2024-11-16 18:09:08,73 days 23:41:34,14 days 14:34:21,88 days 14:15:55,False,...,False,False,False,False,False,False,False,False,True,True
2,1,0.0,0.0,2025-02-13 05:10:44,2025-02-08 23:07:05,2024-10-29 23:53:38,101 days 23:13:27,4 days 06:03:39,106 days 05:17:06,False,...,False,False,False,False,False,False,False,False,False,False
3,1,0.0,1.0,2025-02-13 15:47:10,2025-02-02 03:01:57,2024-11-30 01:33:57,64 days 01:28:00,11 days 12:45:13,75 days 14:13:13,False,...,False,False,False,False,False,False,False,False,False,False
4,1,0.0,0.0,2025-02-13 22:35:48,2024-11-26 19:36:58,2024-11-26 19:36:58,0 days 00:00:00,79 days 02:58:50,79 days 02:58:50,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,1,1.0,1.0,2024-12-28 15:59:50,2024-12-24 06:31:03,2024-11-25 14:29:46,28 days 16:01:17,4 days 09:28:47,33 days 01:30:04,False,...,False,False,False,False,False,False,False,False,True,True
4991,1,1.0,1.0,2025-02-13 21:23:53,2025-01-29 22:49:19,2024-12-27 19:20:15,33 days 03:29:04,14 days 22:34:34,48 days 02:03:38,False,...,False,False,False,False,False,False,False,False,True,True
4992,1,0.0,0.0,2024-11-21 14:55:35,2024-12-27 03:44:56,2024-11-21 14:55:35,35 days 12:49:21,-36 days +11:10:39,0 days 00:00:00,False,...,False,False,False,False,False,False,False,False,True,True
4993,1,0.0,0.0,2025-02-13 03:03:23,2025-02-12 03:03:36,2024-12-17 03:41:05,56 days 23:22:31,0 days 23:59:47,57 days 23:22:18,False,...,False,False,False,False,False,False,False,False,False,False
4994,1,0.0,1.0,2024-11-01 21:00:13,2024-11-01 22:30:59,2024-11-01 21:00:13,0 days 01:30:46,-1 days +22:29:14,0 days 00:00:00,False,...,False,False,False,False,False,False,False,False,False,False